#!/bin/sh

if [ $EUID -ne 0 ]; then
	echo 'This script must be run as root'
	exit 1
fi

cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
cat /etc/pacman.d/mirrorlist.pacnew|awk '/## United States/{flag=1;next}/^$/{flag=0}flag'|sed 's/^#//g' > /etc/pacman.d/mirrorlist.tmp
rankmirrors -n 6 /etc/pacman.d/mirrorlist.tmp > /etc/pacman.d/mirrorlist
